import type { Metadata } from 'next';
import { Saira, Saira_Stencil_One } from 'next/font/google';
import './globals.css';

const geistSans = Saira({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Saira_Stencil_One({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans font-mono antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
